import localFont from 'next/font/local';
import './globals.css';
import NavBar from '@/components/navbar/nav';

export const metadata = {
  title: 'Destiny Eze Portfolio',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <main className="app">
          <NavBar />
          {children}
        </main>
      </body>
    </html>
  );
}
